<a href="https://colab.research.google.com/github/Vanshtiwari15/RNN-IMDB.Project/blob/main/RNN_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
## Sentences
sent=['the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
## One hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5533, 9001, 1892, 661],
 [5533, 9001, 1892, 5672],
 [5533, 9233, 1892, 1364],
 [1994, 7869, 2338, 2515, 5711],
 [1994, 7869, 2338, 2515, 1151],
 [3, 5533, 3556, 1892, 3307],
 [9138, 6372, 8568, 2515]]

In [8]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
## from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs) ## if i use post intead of pre all zeros at last use it once when praticing

[[   0    0    0    0 5533 9001 1892  661]
 [   0    0    0    0 5533 9001 1892 5672]
 [   0    0    0    0 5533 9233 1892 1364]
 [   0    0    0 1994 7869 2338 2515 5711]
 [   0    0    0 1994 7869 2338 2515 1151]
 [   0    0    0    3 5533 3556 1892 3307]
 [   0    0    0    0 9138 6372 8568 2515]]


In [11]:
 ## Feature representaion
 dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')
model.build(input_shape=(None, sent_length))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
print("voc_size =", voc_size)
print("dim =", dim)
print("sent_length =", sent_length)

voc_size = 10000
dim = 10
sent_length = 8


In [15]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 338ms/step


array([[[-4.7522333e-02,  3.7405144e-02,  1.9453391e-03,  3.0785609e-02,
         -4.5984268e-02,  2.9832076e-02,  3.4751046e-02,  2.5782440e-02,
          3.6205020e-02,  1.5561357e-03],
        [-4.7522333e-02,  3.7405144e-02,  1.9453391e-03,  3.0785609e-02,
         -4.5984268e-02,  2.9832076e-02,  3.4751046e-02,  2.5782440e-02,
          3.6205020e-02,  1.5561357e-03],
        [-4.7522333e-02,  3.7405144e-02,  1.9453391e-03,  3.0785609e-02,
         -4.5984268e-02,  2.9832076e-02,  3.4751046e-02,  2.5782440e-02,
          3.6205020e-02,  1.5561357e-03],
        [-4.7522333e-02,  3.7405144e-02,  1.9453391e-03,  3.0785609e-02,
         -4.5984268e-02,  2.9832076e-02,  3.4751046e-02,  2.5782440e-02,
          3.6205020e-02,  1.5561357e-03],
        [-2.2422826e-02, -4.8816577e-03,  2.0471700e-03, -4.9754232e-04,
          1.0437451e-02, -2.7163196e-02, -2.8793538e-02, -4.9643971e-02,
          1.8780936e-02, -8.9716315e-03],
        [-3.2377459e-02,  2.1053102e-02, -1.9426608e-02, -3.

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 5533, 9001, 1892,  661], dtype=int32)

In [17]:
model.predict(embedded_docs[0].reshape(1, -1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step


array([[[-4.7522333e-02,  3.7405144e-02,  1.9453391e-03,  3.0785609e-02,
         -4.5984268e-02,  2.9832076e-02,  3.4751046e-02,  2.5782440e-02,
          3.6205020e-02,  1.5561357e-03],
        [-4.7522333e-02,  3.7405144e-02,  1.9453391e-03,  3.0785609e-02,
         -4.5984268e-02,  2.9832076e-02,  3.4751046e-02,  2.5782440e-02,
          3.6205020e-02,  1.5561357e-03],
        [-4.7522333e-02,  3.7405144e-02,  1.9453391e-03,  3.0785609e-02,
         -4.5984268e-02,  2.9832076e-02,  3.4751046e-02,  2.5782440e-02,
          3.6205020e-02,  1.5561357e-03],
        [-4.7522333e-02,  3.7405144e-02,  1.9453391e-03,  3.0785609e-02,
         -4.5984268e-02,  2.9832076e-02,  3.4751046e-02,  2.5782440e-02,
          3.6205020e-02,  1.5561357e-03],
        [-2.2422826e-02, -4.8816577e-03,  2.0471700e-03, -4.9754232e-04,
          1.0437451e-02, -2.7163196e-02, -2.8793538e-02, -4.9643971e-02,
          1.8780936e-02, -8.9716315e-03],
        [-3.2377459e-02,  2.1053102e-02, -1.9426608e-02, -3.

END TO END Deep Learning Project Using Simple RNN

In [18]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense


In [19]:
## load the imdb dataset

max_features=10000 ##Vocabulary size
(X_train,y_train),(X_test,y_test)=imdb.load_data(num_words=max_features)


## Print the shape of the data
print(f"Training data shape: {X_train.shape}, Training labels shape: {y_train.shape}")
print(f"Testing data shape: {X_test.shape}, Testing labels shape: {y_test.shape}")

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
Training data shape: (25000,), Training labels shape: (25000,)
Testing data shape: (25000,), Testing labels shape: (25000,)


In [20]:
## Inspect a sample review and its label
sample_review=X_train[0]
sample_label=y_train[0]

print(f"sample review (as integers):{sample_review}")
print(f'Sample label: {sample_label}')

sample review (as integers):[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]
Sample label: 1


In [21]:
## Mapping of words index back to words(for understanding)
word_index=imdb.get_word_index()
# word_index
reverse_word_index={value: key for key, value in word_index.items()}
reverse_word_index

1641221/1641221 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


{34701: 'fawn',
 52006: 'tsukino',
 52007: 'nunnery',
 16816: 'sonja',
 63951: 'vani',
 1408: 'woods',
 16115: 'spiders',
 2345: 'hanging',
 2289: 'woody',
 52008: 'trawling',
 52009: "hold's",
 11307: 'comically',
 40830: 'localized',
 30568: 'disobeying',
 52010: "'royale",
 40831: "harpo's",
 52011: 'canet',
 19313: 'aileen',
 52012: 'acurately',
 52013: "diplomat's",
 25242: 'rickman',
 6746: 'arranged',
 52014: 'rumbustious',
 52015: 'familiarness',
 52016: "spider'",
 68804: 'hahahah',
 52017: "wood'",
 40833: 'transvestism',
 34702: "hangin'",
 2338: 'bringing',
 40834: 'seamier',
 34703: 'wooded',
 52018: 'bravora',
 16817: 'grueling',
 1636: 'wooden',
 16818: 'wednesday',
 52019: "'prix",
 34704: 'altagracia',
 52020: 'circuitry',
 11585: 'crotch',
 57766: 'busybody',
 52021: "tart'n'tangy",
 14129: 'burgade',
 52023: 'thrace',
 11038: "tom's",
 52025: 'snuggles',
 29114: 'francesco',
 52027: 'complainers',
 52125: 'templarios',
 40835: '272',
 52028: '273',
 52130: 'zaniacs',

In [22]:
decoded_review=' '.join([reverse_word_index.get(i - 3, '?') for i in sample_review])
decoded_review

"? this film was just brilliant casting location scenery story direction everyone's really suited the part they played and you could just imagine being there robert ? is an amazing actor and now the same being director ? father came from the same scottish island as myself so i loved the fact there was a real connection with this film the witty remarks throughout the film were great it was just brilliant so much that i bought the film as soon as it was released for ? and would recommend it to everyone to watch and the fly fishing was amazing really cried at the end it was so sad and you know what they say if you cry at a film it must have been good and this definitely was also ? to the two little boy's that played the ? of norman and paul they were just brilliant children are often left out of the ? list i think because the stars that play them all grown up are such a big profile for the whole film but these children are amazing and should be praised for what they have done don't you th

In [23]:
from tensorflow.keras.preprocessing import sequence

max_len=500

X_train=sequence.pad_sequences(X_train,maxlen=max_len)
X_test=sequence.pad_sequences(X_test,maxlen=max_len)
X_train

array([[   0,    0,    0, ...,   19,  178,   32],
       [   0,    0,    0, ...,   16,  145,   95],
       [   0,    0,    0, ...,    7,  129,  113],
       ...,
       [   0,    0,    0, ...,    4, 3586,    2],
       [   0,    0,    0, ...,   12,    9,   23],
       [   0,    0,    0, ...,  204,  131,    9]], dtype=int32)

In [24]:
X_train[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [25]:
## Train Simple RNN
model=Sequential()
model.add(Embedding(max_features,128,input_length=max_len)) ## Embedding layer - Taking all the words converting that particular word into a vector of this dimensions
model.add(SimpleRNN(128,activation='relu'))
model.add(Dense(1,activation="sigmoid"))

# Build model with batch size=None (flexible) and sequence length=max_len
model.build(input_shape=(None, max_len))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [26]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 500, 128)       │     1,280,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,313,025 (5.01 MB)

 Trainable params: 1,313,025 (5.01 MB)

 Non-trainable params: 0 (0.00 B)

In [27]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [28]:
## create an instance of EarlyStopping Callback
from tensorflow.keras.callbacks import EarlyStopping
early_stopping=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [31]:
## Train the model with early stopping
history=model.fit(
    X_train,y_train,epochs=10,batch_size=32,
    validation_split=0.2,
    callbacks=[early_stopping]
)

Epoch 1/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 29s 42ms/step - accuracy: 0.6132 - loss: 62670.6211 - val_accuracy: 0.5752 - val_loss: 0.6668
Epoch 2/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 40s 42ms/step - accuracy: 0.6319 - loss: 28.6295 - val_accuracy: 0.6356 - val_loss: 0.6289
Epoch 3/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 26s 42ms/step - accuracy: 0.5760 - loss: nan - val_accuracy: 0.5062 - val_loss: nan
Epoch 4/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 41s 43ms/step - accuracy: 0.4989 - loss: nan - val_accuracy: 0.5062 - val_loss: nan
Epoch 5/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 40s 41ms/step - accuracy: 0.5058 - loss: nan - val_accuracy: 0.5062 - val_loss: nan
Epoch 6/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 41s 40ms/step - accuracy: 0.4944 - loss: nan - val_accuracy: 0.5062 - val_loss: nan
Epoch 7/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 42s 42ms/step - accuracy: 0.4947 - loss: nan - val_accuracy: 0.5062 - val_loss: nan


In [32]:
## Save model file
model.save('simple_rnn_imdb.h5')

In [47]:
## load the pre-trained model with RelU activation
from tensorflow.keras.models import load_model
model=load_model('simple_rnn_imdb.h5')
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 500, 128)       │     1,280,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,313,027 (5.01 MB)

 Trainable params: 1,313,025 (5.01 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)

In [48]:
model.get_weights()

[array([[-0.02128008,  0.09529977,  0.13473062, ...,  0.16772844,
          0.03202025, -0.07405381],
        [ 0.02692948, -0.01495028,  0.11384895, ..., -0.04105876,
          0.06329253,  0.00666775],
        [ 0.10049605,  0.1729673 ,  0.05205643, ..., -0.12911367,
         -0.0665362 ,  0.11079842],
        ...,
        [ 0.06100302,  0.08078413, -0.06874938, ..., -0.00445208,
         -0.05949004,  0.03685942],
        [-0.01563895, -0.05963205,  0.08101008, ...,  0.08807289,
          0.07730415, -0.04997339],
        [-0.07943249, -0.02129703,  0.02111208, ...,  0.03682816,
          0.07504992, -0.00085937]], dtype=float32),
 array([[-0.15496059,  0.108117  , -0.0695639 , ..., -0.03323943,
         -0.08326466,  0.00915416],
        [-0.04560105, -0.01029575, -0.11908557, ...,  0.21114948,
          0.01226958, -0.08514342],
        [-0.15005559, -0.13119303,  0.03557481, ..., -0.0163511 ,
          0.04522915,  0.04517922],
        ...,
        [-0.04454284,  0.07308649,  0.0

In [49]:
# Step 2: Helper Functions
# Function to decode reviews
def decode_review(encoded_review):
    return ' '.join([reverse_word_index.get(i - 3, '?') for i in encoded_review])

# Function to preprocess user input
def preprocess_text(text):
    words = text.lower().split()
    encoded_review = [word_index.get(word, 2) + 3 for word in words]
    padded_review = sequence.pad_sequences([encoded_review], maxlen=500)
    return padded_review

In [50]:
### Prediction  function

def predict_sentiment(review):
  preprocessed_input=preprocess_text(review)

  Prediction=model.predict(preprocessed_input)

  sentiment = 'Positive' if Prediction[0][0] > 0.5 else 'Negative'

  return sentiment, Prediction[0][0]

In [51]:
# Step 4: User Input and Prediction
# Example review for prediction
example_review = "This movie was fanantastic! The acting was great and the plot was thrilling."

sentiment,score=predict_sentiment(example_review)

print(f'Review: {example_review}')
print(f'Sentiment: {sentiment}')
print(f'Prediction Score: {score}')


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 523ms/step
Review: This movie was fanantastic! The acting was great and the plot was thrilling.
Sentiment: Negative
Prediction Score: 0.2714746594429016
